name: CI

on:
  push:
  pull_request:

jobs:
  r-cmd-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libfribidi-dev \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libglpk-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            pkg-config \
            libtiff5-dev \
            libwebp-dev \
            libxml2-dev \
            libx11-dev

      - uses: r-lib/actions/setup-renv@v2

      - name: Run tests
        run: R -q -e 'testthat::test_dir("tests/testthat")'

      - name: Lint
        run: R -q -e 'lintr::lint_dir("R")'
